/**
 * No Waste - Datenbasis
 * 73 Rezepte über Frühstück, Mittag/Abend und Süßspeisen, mit gewichteten
 * und als "essenziell" (Hauptzutat) oder optional (Nebenzutat) markierten
 * Zutaten, Allergenen (angelehnt an die 14 EU-Hauptallergene), Nährwerten
 * und Zubereitungsschritten.
 */

const REZEPTE = [
  {
    id: 1,
    name: "Rührei mit Speck",
    icon: "🍳",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "omnivor",
    allergene: ["Ei", "Laktose"],
    naehrwerte: { kcal: 350, eiweiss_g: 22, fett_g: 28, kohlenhydrate_g: 2 },
    zutaten: [
      { name: "Ei", gewicht: 5, essenziell: true },
      { name: "Speck", gewicht: 3, essenziell: true },
      { name: "Butter", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Speck in einer Pfanne knusprig braten.", "Eier verquirlen und dazugeben.", "Unter Rühren stocken lassen, mit Butter verfeinern."],
  },
  {
    id: 2,
    name: "Porridge mit Beeren",
    icon: "🥣",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose", "Gluten"],
    naehrwerte: { kcal: 320, eiweiss_g: 10, fett_g: 7, kohlenhydrate_g: 55 },
    zutaten: [
      { name: "Haferflocken", gewicht: 4, essenziell: true },
      { name: "Milch", gewicht: 3, essenziell: true },
      { name: "Beeren", gewicht: 2, essenziell: false },
      { name: "Honig", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Haferflocken mit Milch in einem Topf aufkochen.", "Bei kleiner Hitze 5 Minuten quellen lassen.", "Mit Beeren und Honig servieren."],
  },
  {
    id: 3,
    name: "Pfannkuchen",
    icon: "🥞",
    kategorie: "Frühstück",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose", "Ei"],
    naehrwerte: { kcal: 280, eiweiss_g: 9, fett_g: 8, kohlenhydrate_g: 42 },
    zutaten: [
      { name: "Mehl", gewicht: 4, essenziell: true },
      { name: "Milch", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Mehl, Milch und Ei zu einem glatten Teig verrühren.", "Portionsweise in der Pfanne goldbraun backen.", "Nach Belieben mit Zucker bestreuen."],
  },
  {
    id: 4,
    name: "Avocado-Toast",
    icon: "🥑",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Ei"],
    naehrwerte: { kcal: 310, eiweiss_g: 9, fett_g: 18, kohlenhydrate_g: 28 },
    zutaten: [
      { name: "Brot", gewicht: 3, essenziell: true },
      { name: "Avocado", gewicht: 4, essenziell: true },
      { name: "Ei", gewicht: 2, essenziell: false },
      { name: "Chili", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Brot toasten.", "Avocado zerdrücken und würzen.", "Auf dem Toast verteilen, optional mit Ei und Chili toppen."],
  },
  {
    id: 5,
    name: "Nuss-Granola",
    icon: "🥜",
    kategorie: "Frühstück",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Nüsse"],
    naehrwerte: { kcal: 390, eiweiss_g: 11, fett_g: 18, kohlenhydrate_g: 45 },
    zutaten: [
      { name: "Haferflocken", gewicht: 4, essenziell: true },
      { name: "Nüsse", gewicht: 3, essenziell: true },
      { name: "Honig", gewicht: 2, essenziell: false },
      { name: "Trockenfrüchte", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Haferflocken und Nüsse mischen.", "Mit Honig vermengen und auf einem Blech verteilen.", "Bei 160°C ca. 15 Minuten goldbraun backen, Trockenfrüchte untermischen."],
  },
  {
    id: 6,
    name: "Hühnercurry",
    icon: "🍛",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "omnivor",
    allergene: [],
    naehrwerte: { kcal: 480, eiweiss_g: 32, fett_g: 22, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 5, essenziell: true },
      { name: "Curry", gewicht: 2, essenziell: true },
      { name: "Kokosmilch", gewicht: 3, essenziell: true },
      { name: "Reis", gewicht: 2, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust in Streifen schneiden und anbraten.", "Zwiebel mitdünsten, Curry hinzufügen.", "Mit Kokosmilch ablöschen und köcheln lassen, mit Reis servieren."],
  },
  {
    id: 7,
    name: "Gemüsepfanne",
    icon: "🥘",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 260, eiweiss_g: 6, fett_g: 9, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Paprika", gewicht: 3, essenziell: true },
      { name: "Zucchini", gewicht: 3, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Reis", gewicht: 2, essenziell: false },
      { name: "Olivenöl", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gemüse waschen und in Stücke schneiden.", "In Olivenöl mit Zwiebel anbraten.", "Mit Gewürzen abschmecken und mit Reis servieren."],
  },
  {
    id: 8,
    name: "Linsensuppe",
    icon: "🍲",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 40,
    ernaehrungskategorie: "vegan",
    allergene: ["Sellerie"],
    naehrwerte: { kcal: 310, eiweiss_g: 18, fett_g: 3, kohlenhydrate_g: 48 },
    zutaten: [
      { name: "Linsen", gewicht: 4, essenziell: true },
      { name: "Karotte", gewicht: 2, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Sellerie", gewicht: 1, essenziell: false },
      { name: "Kreuzkümmel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Linsen abspülen.", "Mit Karotte, Zwiebel und Sellerie in Brühe weich kochen.", "Mit Kreuzkümmel abschmecken."],
  },
  {
    id: 9,
    name: "Käsespätzle",
    icon: "🧀",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 520, eiweiss_g: 20, fett_g: 24, kohlenhydrate_g: 55 },
    zutaten: [
      { name: "Spätzle", gewicht: 4, essenziell: true },
      { name: "Käse", gewicht: 3, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Butter", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Spätzle in Salzwasser kochen.", "Lagenweise mit Käse in einer Pfanne schichten und schmelzen lassen.", "Mit gerösteten Zwiebeln servieren."],
  },
  {
    id: 10,
    name: "Lachs mit Gemüse",
    icon: "🐟",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Fisch"],
    naehrwerte: { kcal: 420, eiweiss_g: 34, fett_g: 26, kohlenhydrate_g: 6 },
    zutaten: [
      { name: "Lachs", gewicht: 5, essenziell: true },
      { name: "Brokkoli", gewicht: 2, essenziell: false },
      { name: "Zitrone", gewicht: 1, essenziell: false },
      { name: "Olivenöl", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Lachs mit Zitrone würzen.", "In Olivenöl braten oder im Ofen garen.", "Mit gedünstetem Brokkoli servieren."],
  },
  {
    id: 11,
    name: "Vegane Buddha Bowl",
    icon: "🥗",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegan",
    allergene: ["Sesam"],
    naehrwerte: { kcal: 450, eiweiss_g: 16, fett_g: 18, kohlenhydrate_g: 55 },
    zutaten: [
      { name: "Kichererbsen", gewicht: 3, essenziell: true },
      { name: "Quinoa", gewicht: 3, essenziell: true },
      { name: "Avocado", gewicht: 2, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Tahini", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Quinoa kochen.", "Kichererbsen anbraten und würzen.", "Alles mit Avocado und Paprika in einer Bowl anrichten, mit Tahini beträufeln."],
  },
  {
    id: 12,
    name: "Rindergulasch",
    icon: "🍖",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 90,
    ernaehrungskategorie: "omnivor",
    allergene: [],
    naehrwerte: { kcal: 490, eiweiss_g: 35, fett_g: 24, kohlenhydrate_g: 20 },
    zutaten: [
      { name: "Rindfleisch", gewicht: 5, essenziell: true },
      { name: "Paprikapulver", gewicht: 1, essenziell: true },
      { name: "Zwiebel", gewicht: 2, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Kartoffel", gewicht: 2, essenziell: false },
    ],
    zubereitung: ["Rindfleisch scharf anbraten.", "Zwiebel und Paprika mitdünsten, mit Paprikapulver würzen.", "Mit Flüssigkeit aufgießen und 1,5 Stunden schmoren, mit Kartoffeln servieren."],
  },
  {
    id: 13,
    name: "Falafel-Wrap",
    icon: "🌯",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 400, eiweiss_g: 14, fett_g: 14, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Kichererbsen", gewicht: 4, essenziell: true },
      { name: "Tortilla", gewicht: 2, essenziell: true },
      { name: "Joghurtsauce", gewicht: 1, essenziell: false },
      { name: "Salat", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Kichererbsen pürieren und zu Bällchen formen.", "In der Pfanne goldbraun braten.", "In der Tortilla mit Salat und Joghurtsauce einrollen."],
  },
  {
    id: 14,
    name: "Pasta Aglio e Olio",
    icon: "🍝",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 420, eiweiss_g: 12, fett_g: 14, kohlenhydrate_g: 60 },
    zutaten: [
      { name: "Pasta", gewicht: 4, essenziell: true },
      { name: "Knoblauch", gewicht: 2, essenziell: true },
      { name: "Olivenöl", gewicht: 1, essenziell: false },
      { name: "Chili", gewicht: 1, essenziell: false },
      { name: "Petersilie", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Pasta in Salzwasser kochen.", "Knoblauch in Olivenöl goldgelb anbraten.", "Pasta untermengen, mit Chili und Petersilie verfeinern."],
  },
  {
    id: 15,
    name: "Spaghetti Bolognese",
    icon: "🍜",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 45,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 560, eiweiss_g: 28, fett_g: 20, kohlenhydrate_g: 62 },
    zutaten: [
      { name: "Spaghetti", gewicht: 4, essenziell: true },
      { name: "Hackfleisch", gewicht: 4, essenziell: true },
      { name: "Tomatensauce", gewicht: 2, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Parmesan", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Zwiebel andünsten, Hackfleisch anbraten.", "Tomatensauce dazugeben und köcheln lassen.", "Mit gekochten Spaghetti und Parmesan servieren."],
  },
  {
    id: 16,
    name: "Kokos-Kichererbsen-Curry",
    icon: "🍛",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 430, eiweiss_g: 14, fett_g: 20, kohlenhydrate_g: 48 },
    zutaten: [
      { name: "Kokosmilch", gewicht: 3, essenziell: true },
      { name: "Curry", gewicht: 2, essenziell: true },
      { name: "Kichererbsen", gewicht: 3, essenziell: true },
      { name: "Spinat", gewicht: 2, essenziell: false },
      { name: "Reis", gewicht: 2, essenziell: false },
    ],
    zubereitung: ["Curry kurz in einem Topf anrösten.", "Kokosmilch und Kichererbsen dazugeben und 10 Minuten köcheln lassen.", "Spinat unterrühren und mit Reis servieren."],
  },
  {
    id: 17,
    name: "Thunfisch-Salat",
    icon: "🥙",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Fisch", "Ei"],
    naehrwerte: { kcal: 310, eiweiss_g: 30, fett_g: 14, kohlenhydrate_g: 10 },
    zutaten: [
      { name: "Thunfisch", gewicht: 4, essenziell: true },
      { name: "Salat", gewicht: 2, essenziell: true },
      { name: "Mais", gewicht: 1, essenziell: false },
      { name: "Ei", gewicht: 1, essenziell: false },
      { name: "Olivenöl", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Salat waschen und in eine Schüssel geben.", "Thunfisch, Mais und Ei darauf verteilen.", "Mit Olivenöl beträufeln und vermengen."],
  },
  {
    id: 18,
    name: "Chili con Carne",
    icon: "🌶️",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 40,
    ernaehrungskategorie: "omnivor",
    allergene: [],
    naehrwerte: { kcal: 420, eiweiss_g: 28, fett_g: 18, kohlenhydrate_g: 30 },
    zutaten: [
      { name: "Hackfleisch", gewicht: 4, essenziell: true },
      { name: "Kidneybohnen", gewicht: 3, essenziell: true },
      { name: "Tomatensauce", gewicht: 2, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Mais", gewicht: 1, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hackfleisch mit Zwiebel in einem Topf anbraten.", "Tomatensauce, Kidneybohnen und Mais dazugeben.", "20 Minuten köcheln lassen und mit Paprika abschmecken."],
  },
  {
    id: 19,
    name: "Tofu-Pfanne",
    icon: "🥢",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegan",
    allergene: ["Soja"],
    naehrwerte: { kcal: 350, eiweiss_g: 20, fett_g: 14, kohlenhydrate_g: 32 },
    zutaten: [
      { name: "Tofu", gewicht: 4, essenziell: true },
      { name: "Sojasauce", gewicht: 1, essenziell: true },
      { name: "Brokkoli", gewicht: 2, essenziell: false },
      { name: "Reis", gewicht: 2, essenziell: false },
      { name: "Ingwer", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Tofu würfeln und in einer Pfanne knusprig anbraten.", "Brokkoli und Ingwer dazugeben und kurz mitbraten.", "Mit Sojasauce ablöschen und mit Reis servieren."],
  },
  {
    id: 20,
    name: "Schokoladenpudding",
    icon: "🍫",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 260, eiweiss_g: 7, fett_g: 9, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Milch", gewicht: 4, essenziell: true },
      { name: "Kakao", gewicht: 3, essenziell: true },
      { name: "Maisstärke", gewicht: 1, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Milch mit Kakao und Zucker erhitzen.", "Maisstärke einrühren, bis die Masse eindickt.", "In Gläser füllen und kalt stellen."],
  },
  {
    id: 21,
    name: "Apfelstrudel",
    icon: "🥧",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 50,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 310, eiweiss_g: 4, fett_g: 12, kohlenhydrate_g: 46 },
    zutaten: [
      { name: "Äpfel", gewicht: 4, essenziell: true },
      { name: "Blätterteig", gewicht: 3, essenziell: true },
      { name: "Zimt", gewicht: 1, essenziell: false },
      { name: "Rosinen", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Äpfel schälen, schneiden und mit Zimt vermengen.", "Auf den Blätterteig geben, Rosinen dazugeben.", "Einrollen und bei 180°C ca. 30 Minuten backen."],
  },
  {
    id: 22,
    name: "Obstsalat",
    icon: "🍓",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 150, eiweiss_g: 2, fett_g: 1, kohlenhydrate_g: 35 },
    zutaten: [
      { name: "Äpfel", gewicht: 2, essenziell: true },
      { name: "Banane", gewicht: 2, essenziell: true },
      { name: "Orange", gewicht: 1, essenziell: false },
      { name: "Trauben", gewicht: 1, essenziell: false },
      { name: "Honig", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Obst waschen, schälen und in mundgerechte Stücke schneiden.", "Alle Zutaten in einer Schüssel vermengen.", "Mit etwas Honig beträufeln und servieren."],
  },
  {
    id: 23,
    name: "Kaiserschmarrn",
    icon: "🍮",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose", "Ei"],
    naehrwerte: { kcal: 430, eiweiss_g: 12, fett_g: 16, kohlenhydrate_g: 58 },
    zutaten: [
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Milch", gewicht: 2, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Rosinen", gewicht: 1, essenziell: false },
      { name: "Puderzucker", gewicht: 1, essenziell: false },
      { name: "Apfelmus", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Mehl, Milch und Eigelb zu einem Teig verrühren.", "Eiweiß steif schlagen und unterheben, in der Pfanne backen.", "Zerreißen und mit Puderzucker und Apfelmus servieren."],
  },

  // ---------- Frühstück (neu) ----------
  {
    id: 24,
    name: "Bircher Müsli",
    icon: "🥣",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 340, eiweiss_g: 12, fett_g: 9, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Haferflocken", gewicht: 4, essenziell: true },
      { name: "Äpfel", gewicht: 3, essenziell: true },
      { name: "Joghurt", gewicht: 2, essenziell: false },
      { name: "Nüsse", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Haferflocken mit Joghurt vermengen und kurz quellen lassen.", "Äpfel reiben und untermischen.", "Mit Nüssen bestreut servieren."],
  },
  {
    id: 25,
    name: "Smoothie Bowl",
    icon: "🍓",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten", "Nüsse"],
    naehrwerte: { kcal: 280, eiweiss_g: 6, fett_g: 7, kohlenhydrate_g: 50 },
    zutaten: [
      { name: "Banane", gewicht: 3, essenziell: true },
      { name: "Beeren", gewicht: 3, essenziell: true },
      { name: "Haferflocken", gewicht: 1, essenziell: false },
      { name: "Nüsse", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Banane und Beeren pürieren.", "In eine Schüssel füllen.", "Mit Haferflocken und Nüssen toppen."],
  },
  {
    id: 26,
    name: "Bagel mit Lachs",
    icon: "🥯",
    kategorie: "Frühstück",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Gluten", "Fisch", "Laktose"],
    naehrwerte: { kcal: 420, eiweiss_g: 24, fett_g: 20, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Bagel", gewicht: 4, essenziell: true },
      { name: "Lachs", gewicht: 4, essenziell: true },
      { name: "Frischkäse", gewicht: 2, essenziell: false },
      { name: "Zitrone", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Bagel aufschneiden und toasten.", "Mit Frischkäse bestreichen.", "Mit Lachs und Zitrone belegen."],
  },
  {
    id: 27,
    name: "French Toast",
    icon: "🍞",
    kategorie: "Frühstück",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Ei", "Laktose"],
    naehrwerte: { kcal: 360, eiweiss_g: 12, fett_g: 14, kohlenhydrate_g: 46 },
    zutaten: [
      { name: "Brot", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Milch", gewicht: 2, essenziell: true },
      { name: "Zimt", gewicht: 1, essenziell: false },
      { name: "Honig", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Ei und Milch verquirlen, mit Zimt würzen.", "Brotscheiben darin wenden.", "In der Pfanne goldbraun braten und mit Honig servieren."],
  },
  {
    id: 28,
    name: "Shakshuka",
    icon: "🍳",
    kategorie: "Frühstück",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Ei"],
    naehrwerte: { kcal: 310, eiweiss_g: 16, fett_g: 18, kohlenhydrate_g: 18 },
    zutaten: [
      { name: "Ei", gewicht: 4, essenziell: true },
      { name: "Tomatensauce", gewicht: 3, essenziell: true },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Zwiebel und Paprika in der Pfanne andünsten.", "Tomatensauce dazugeben und köcheln lassen.", "Mulden formen, Eier hineingeben und stocken lassen."],
  },
  {
    id: 29,
    name: "Topfen mit Früchten",
    icon: "🍨",
    kategorie: "Frühstück",
    zubereitungszeit_min: 5,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 220, eiweiss_g: 18, fett_g: 5, kohlenhydrate_g: 24 },
    zutaten: [
      { name: "Topfen", gewicht: 4, essenziell: true },
      { name: "Beeren", gewicht: 2, essenziell: false },
      { name: "Honig", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Topfen in eine Schüssel geben.", "Mit Beeren toppen.", "Mit Honig beträufeln."],
  },
  {
    id: 30,
    name: "Frühstücks-Burrito",
    icon: "🌯",
    kategorie: "Frühstück",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Ei", "Laktose"],
    naehrwerte: { kcal: 400, eiweiss_g: 18, fett_g: 20, kohlenhydrate_g: 36 },
    zutaten: [
      { name: "Tortilla", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Käse", gewicht: 2, essenziell: false },
      { name: "Avocado", gewicht: 1, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Eier in der Pfanne verrühren und stocken lassen.", "Mit Käse, Avocado und Paprika auf die Tortilla geben.", "Einrollen und servieren."],
  },
  {
    id: 31,
    name: "Hafer-Pancakes",
    icon: "🥞",
    kategorie: "Frühstück",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Ei"],
    naehrwerte: { kcal: 310, eiweiss_g: 13, fett_g: 8, kohlenhydrate_g: 46 },
    zutaten: [
      { name: "Haferflocken", gewicht: 4, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Banane", gewicht: 2, essenziell: true },
      { name: "Honig", gewicht: 1, essenziell: false },
      { name: "Zimt", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Haferflocken, Ei und Banane pürieren.", "Portionsweise in der Pfanne backen.", "Mit Honig und Zimt servieren."],
  },
  {
    id: 32,
    name: "Rühr-Tofu",
    icon: "🥘",
    kategorie: "Frühstück",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegan",
    allergene: ["Soja"],
    naehrwerte: { kcal: 260, eiweiss_g: 18, fett_g: 16, kohlenhydrate_g: 8 },
    zutaten: [
      { name: "Tofu", gewicht: 4, essenziell: true },
      { name: "Kurkuma", gewicht: 1, essenziell: true },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Tofu zerbröseln und mit Kurkuma würzen.", "In der Pfanne anbraten.", "Paprika und Zwiebel untermischen."],
  },
  {
    id: 33,
    name: "Energie-Smoothie",
    icon: "🥤",
    kategorie: "Frühstück",
    zubereitungszeit_min: 5,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 260, eiweiss_g: 7, fett_g: 4, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Banane", gewicht: 3, essenziell: true },
      { name: "Haferflocken", gewicht: 1, essenziell: false },
      { name: "Honig", gewicht: 1, essenziell: false },
      { name: "Beeren", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Alle Zutaten in einen Mixer geben.", "Fein pürieren.", "In ein Glas füllen und servieren."],
  },

  // ---------- Mittag/Abend (neu) ----------
  {
    id: 34,
    name: "Margherita Pizza",
    icon: "🍕",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 520, eiweiss_g: 20, fett_g: 18, kohlenhydrate_g: 66 },
    zutaten: [
      { name: "Pizzateig", gewicht: 4, essenziell: true },
      { name: "Tomatensauce", gewicht: 2, essenziell: true },
      { name: "Mozzarella", gewicht: 3, essenziell: true },
      { name: "Basilikum", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Pizzateig ausrollen und mit Tomatensauce bestreichen.", "Mit Mozzarella belegen.", "Bei hoher Hitze backen, mit Basilikum garnieren."],
  },
  {
    id: 35,
    name: "Thai Green Curry",
    icon: "🍛",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "omnivor",
    allergene: [],
    naehrwerte: { kcal: 460, eiweiss_g: 28, fett_g: 24, kohlenhydrate_g: 30 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Kokosmilch", gewicht: 3, essenziell: true },
      { name: "Curry", gewicht: 2, essenziell: true },
      { name: "Reis", gewicht: 2, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust anbraten.", "Curry kurz mitrösten, mit Kokosmilch ablöschen.", "Köcheln lassen und mit Reis servieren."],
  },
  {
    id: 36,
    name: "Burger",
    icon: "🍔",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 560, eiweiss_g: 28, fett_g: 30, kohlenhydrate_g: 40 },
    zutaten: [
      { name: "Hackfleisch", gewicht: 4, essenziell: true },
      { name: "Burger-Brötchen", gewicht: 3, essenziell: true },
      { name: "Käse", gewicht: 1, essenziell: false },
      { name: "Salat", gewicht: 1, essenziell: false },
      { name: "Ketchup", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Faschierte Laibchen formen und braten.", "Brötchen aufschneiden und toasten.", "Mit Käse, Salat und Ketchup belegen."],
  },
  {
    id: 37,
    name: "Quiche Lorraine",
    icon: "🥧",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 50,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Ei", "Laktose"],
    naehrwerte: { kcal: 480, eiweiss_g: 18, fett_g: 32, kohlenhydrate_g: 30 },
    zutaten: [
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Speck", gewicht: 3, essenziell: true },
      { name: "Käse", gewicht: 2, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Mürbteig aus Mehl herstellen und in eine Form drücken.", "Ei, Speck, Käse und Zwiebel vermengen und darauf verteilen.", "Bei 180°C ca. 35 Minuten backen."],
  },
  {
    id: 38,
    name: "Risotto",
    icon: "🍚",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 420, eiweiss_g: 10, fett_g: 12, kohlenhydrate_g: 62 },
    zutaten: [
      { name: "Reis", gewicht: 4, essenziell: true },
      { name: "Parmesan", gewicht: 2, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Butter", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Zwiebel in Butter andünsten.", "Reis zugeben und nach und nach mit Brühe ablöschen, rühren.", "Mit Parmesan verfeinern."],
  },
  {
    id: 39,
    name: "Döner-Bowl",
    icon: "🥙",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "omnivor",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 450, eiweiss_g: 30, fett_g: 16, kohlenhydrate_g: 42 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Reis", gewicht: 2, essenziell: true },
      { name: "Salat", gewicht: 1, essenziell: false },
      { name: "Joghurtsauce", gewicht: 1, essenziell: false },
      { name: "Mais", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust würzen und anbraten.", "Reis kochen.", "Alles mit Salat, Mais und Joghurtsauce in einer Bowl anrichten."],
  },
  {
    id: 40,
    name: "Poke Bowl",
    icon: "🍣",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Fisch", "Soja"],
    naehrwerte: { kcal: 430, eiweiss_g: 26, fett_g: 16, kohlenhydrate_g: 44 },
    zutaten: [
      { name: "Lachs", gewicht: 4, essenziell: true },
      { name: "Reis", gewicht: 3, essenziell: true },
      { name: "Avocado", gewicht: 1, essenziell: false },
      { name: "Mais", gewicht: 1, essenziell: false },
      { name: "Sojasauce", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reis kochen und abkühlen lassen.", "Lachs würfeln.", "Mit Avocado, Mais und Sojasauce in einer Bowl anrichten."],
  },
  {
    id: 41,
    name: "Schnitzel mit Erdäpfelsalat",
    icon: "🍖",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 35,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 540, eiweiss_g: 32, fett_g: 28, kohlenhydrate_g: 36 },
    zutaten: [
      { name: "Schnitzel", gewicht: 5, essenziell: true },
      { name: "Kartoffel", gewicht: 2, essenziell: true },
      { name: "Zitrone", gewicht: 1, essenziell: false },
      { name: "Salat", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Schnitzel panieren und goldbraun braten.", "Kartoffeln kochen und zu einem Salat verarbeiten.", "Mit Zitrone servieren."],
  },
  {
    id: 42,
    name: "Pad Thai",
    icon: "🍜",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegan",
    allergene: ["Soja", "Nüsse"],
    naehrwerte: { kcal: 440, eiweiss_g: 16, fett_g: 14, kohlenhydrate_g: 58 },
    zutaten: [
      { name: "Reisnudeln", gewicht: 4, essenziell: true },
      { name: "Tofu", gewicht: 3, essenziell: true },
      { name: "Sojasauce", gewicht: 1, essenziell: false },
      { name: "Nüsse", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reisnudeln nach Packungsangabe zubereiten.", "Tofu anbraten und mit Sojasauce würzen.", "Mit Nudeln vermengen und mit Nüssen bestreuen."],
  },
  {
    id: 43,
    name: "Tacos",
    icon: "🌮",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 420, eiweiss_g: 22, fett_g: 18, kohlenhydrate_g: 36 },
    zutaten: [
      { name: "Hackfleisch", gewicht: 4, essenziell: true },
      { name: "Tortilla", gewicht: 3, essenziell: true },
      { name: "Salat", gewicht: 1, essenziell: false },
      { name: "Käse", gewicht: 1, essenziell: false },
      { name: "Mais", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hackfleisch würzen und anbraten.", "Tortillas kurz erwärmen.", "Mit Hackfleisch, Salat, Käse und Mais befüllen."],
  },
  {
    id: 44,
    name: "Ratatouille",
    icon: "🍆",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 35,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 220, eiweiss_g: 5, fett_g: 9, kohlenhydrate_g: 28 },
    zutaten: [
      { name: "Zucchini", gewicht: 3, essenziell: true },
      { name: "Paprika", gewicht: 3, essenziell: true },
      { name: "Tomatensauce", gewicht: 2, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Knoblauch", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gemüse in Stücke schneiden.", "Mit Zwiebel und Knoblauch andünsten.", "Mit Tomatensauce vermengen und schmoren lassen."],
  },
  {
    id: 45,
    name: "Minestrone",
    icon: "🍲",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten", "Sellerie"],
    naehrwerte: { kcal: 280, eiweiss_g: 10, fett_g: 4, kohlenhydrate_g: 50 },
    zutaten: [
      { name: "Tomatensauce", gewicht: 3, essenziell: true },
      { name: "Pasta", gewicht: 3, essenziell: true },
      { name: "Karotte", gewicht: 1, essenziell: false },
      { name: "Sellerie", gewicht: 1, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gemüse klein schneiden und andünsten.", "Mit Tomatensauce und Brühe aufgießen.", "Pasta mitkochen, bis sie gar ist."],
  },
  {
    id: 46,
    name: "Caesar Salad",
    icon: "🥗",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "omnivor",
    allergene: ["Laktose", "Gluten"],
    naehrwerte: { kcal: 380, eiweiss_g: 28, fett_g: 22, kohlenhydrate_g: 16 },
    zutaten: [
      { name: "Salat", gewicht: 3, essenziell: true },
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Parmesan", gewicht: 1, essenziell: false },
      { name: "Brot", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust braten und in Streifen schneiden.", "Salat waschen und in eine Schüssel geben.", "Mit Hühnerbrust, Parmesan und gerösteten Brotwürfeln servieren."],
  },
  {
    id: 47,
    name: "Gyros-Teller",
    icon: "🥙",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 480, eiweiss_g: 30, fett_g: 22, kohlenhydrate_g: 36 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Tortilla", gewicht: 2, essenziell: true },
      { name: "Joghurtsauce", gewicht: 1, essenziell: false },
      { name: "Salat", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust würzen und scharf anbraten.", "Tortilla kurz erwärmen.", "Mit Salat und Joghurtsauce anrichten."],
  },
  {
    id: 48,
    name: "Burrito Bowl",
    icon: "🥣",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 420, eiweiss_g: 16, fett_g: 14, kohlenhydrate_g: 58 },
    zutaten: [
      { name: "Reis", gewicht: 3, essenziell: true },
      { name: "Kidneybohnen", gewicht: 3, essenziell: true },
      { name: "Mais", gewicht: 1, essenziell: false },
      { name: "Avocado", gewicht: 1, essenziell: false },
      { name: "Salat", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reis kochen.", "Kidneybohnen erwärmen und würzen.", "Alles mit Mais, Avocado und Salat in einer Bowl anrichten."],
  },
  {
    id: 49,
    name: "Chicken Wrap",
    icon: "🌯",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "omnivor",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 400, eiweiss_g: 26, fett_g: 14, kohlenhydrate_g: 40 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Tortilla", gewicht: 3, essenziell: true },
      { name: "Salat", gewicht: 1, essenziell: false },
      { name: "Joghurtsauce", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust anbraten und in Streifen schneiden.", "Tortilla mit Salat und Joghurtsauce bestreichen.", "Hühnerbrust einrollen."],
  },
  {
    id: 50,
    name: "Fish and Chips",
    icon: "🐟",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 35,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Fisch", "Gluten"],
    naehrwerte: { kcal: 560, eiweiss_g: 30, fett_g: 28, kohlenhydrate_g: 48 },
    zutaten: [
      { name: "Lachs", gewicht: 4, essenziell: true },
      { name: "Kartoffel", gewicht: 4, essenziell: true },
      { name: "Zitrone", gewicht: 1, essenziell: false },
      { name: "Erbsen", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Kartoffeln in Spalten schneiden und backen.", "Lachs panieren und braten.", "Mit Zitrone und Erbsen servieren."],
  },
  {
    id: 51,
    name: "Gemüse-Lasagne",
    icon: "🍝",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 50,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 460, eiweiss_g: 18, fett_g: 20, kohlenhydrate_g: 50 },
    zutaten: [
      { name: "Lasagneplatten", gewicht: 4, essenziell: true },
      { name: "Tomatensauce", gewicht: 2, essenziell: true },
      { name: "Käse", gewicht: 3, essenziell: true },
      { name: "Zucchini", gewicht: 1, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gemüse klein schneiden und andünsten.", "Lagenweise mit Lasagneplatten, Tomatensauce und Käse schichten.", "Bei 180°C ca. 30 Minuten backen."],
  },
  {
    id: 52,
    name: "Kartoffelgulasch",
    icon: "🥔",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 40,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 300, eiweiss_g: 7, fett_g: 9, kohlenhydrate_g: 46 },
    zutaten: [
      { name: "Kartoffel", gewicht: 4, essenziell: true },
      { name: "Paprikapulver", gewicht: 1, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Zwiebel andünsten und mit Paprikapulver bestäuben.", "Kartoffel würfeln und dazugeben.", "Mit Flüssigkeit aufgießen und weich köcheln lassen."],
  },
  {
    id: 53,
    name: "Reispfanne mit Spiegelei",
    icon: "🍚",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Ei", "Soja"],
    naehrwerte: { kcal: 380, eiweiss_g: 14, fett_g: 14, kohlenhydrate_g: 48 },
    zutaten: [
      { name: "Reis", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 3, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Sojasauce", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reis braten, Gemüse dazugeben.", "Mit Sojasauce würzen.", "Mit einem Spiegelei servieren."],
  },
  {
    id: 54,
    name: "Couscous-Salat",
    icon: "🥗",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 320, eiweiss_g: 9, fett_g: 8, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Couscous", gewicht: 4, essenziell: true },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Zitrone", gewicht: 1, essenziell: false },
      { name: "Petersilie", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Couscous mit heißer Brühe übergießen und quellen lassen.", "Paprika klein schneiden und untermischen.", "Mit Zitrone und Petersilie abschmecken."],
  },
  {
    id: 55,
    name: "Miso-Suppe mit Tofu",
    icon: "🍜",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegan",
    allergene: ["Soja"],
    naehrwerte: { kcal: 180, eiweiss_g: 12, fett_g: 8, kohlenhydrate_g: 12 },
    zutaten: [
      { name: "Tofu", gewicht: 3, essenziell: true },
      { name: "Misopaste", gewicht: 2, essenziell: true },
      { name: "Spinat", gewicht: 1, essenziell: false },
      { name: "Ingwer", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Misopaste in heißem Wasser auflösen.", "Tofu würfeln und dazugeben.", "Mit Spinat und Ingwer verfeinern."],
  },
  {
    id: 56,
    name: "Gnocchi mit Pesto",
    icon: "🍝",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Nüsse", "Laktose"],
    naehrwerte: { kcal: 460, eiweiss_g: 12, fett_g: 20, kohlenhydrate_g: 58 },
    zutaten: [
      { name: "Gnocchi", gewicht: 4, essenziell: true },
      { name: "Pesto", gewicht: 2, essenziell: true },
      { name: "Parmesan", gewicht: 1, essenziell: false },
      { name: "Tomatensauce", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gnocchi in Salzwasser kochen, bis sie aufsteigen.", "Mit Pesto vermengen.", "Mit Parmesan bestreuen."],
  },
  {
    id: 57,
    name: "Hähnchen-Teriyaki",
    icon: "🍗",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 25,
    ernaehrungskategorie: "omnivor",
    allergene: ["Soja"],
    naehrwerte: { kcal: 430, eiweiss_g: 30, fett_g: 14, kohlenhydrate_g: 42 },
    zutaten: [
      { name: "Hühnerbrust", gewicht: 4, essenziell: true },
      { name: "Sojasauce", gewicht: 2, essenziell: true },
      { name: "Reis", gewicht: 2, essenziell: false },
      { name: "Ingwer", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hühnerbrust in Stücke schneiden und anbraten.", "Mit Sojasauce und Ingwer ablöschen und karamellisieren lassen.", "Mit Reis servieren."],
  },
  {
    id: 58,
    name: "Kürbissuppe",
    icon: "🎃",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "vegan",
    allergene: [],
    naehrwerte: { kcal: 220, eiweiss_g: 4, fett_g: 10, kohlenhydrate_g: 28 },
    zutaten: [
      { name: "Kürbis", gewicht: 4, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Kokosmilch", gewicht: 2, essenziell: false },
      { name: "Ingwer", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Kürbis schälen und würfeln.", "Mit Zwiebel andünsten und mit Brühe weich kochen.", "Pürieren und mit Kokosmilch und Ingwer verfeinern."],
  },
  {
    id: 59,
    name: "Erdäpfel-Gröstl",
    icon: "🥘",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "omnivor",
    allergene: ["Ei"],
    naehrwerte: { kcal: 420, eiweiss_g: 16, fett_g: 22, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Kartoffel", gewicht: 4, essenziell: true },
      { name: "Speck", gewicht: 3, essenziell: true },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Ei", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Kartoffeln kochen, abkühlen lassen und würfeln.", "Mit Speck und Zwiebel in der Pfanne anbraten.", "Mit einem Spiegelei servieren."],
  },
  {
    id: 60,
    name: "Bauernsalat mit Feta",
    icon: "🥗",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 10,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 280, eiweiss_g: 10, fett_g: 20, kohlenhydrate_g: 12 },
    zutaten: [
      { name: "Salat", gewicht: 2, essenziell: true },
      { name: "Feta", gewicht: 3, essenziell: true },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
      { name: "Olivenöl", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Gemüse waschen und in Stücke schneiden.", "Mit Feta vermengen.", "Mit Olivenöl anmachen."],
  },
  {
    id: 61,
    name: "Shepherd's Pie",
    icon: "🥧",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 60,
    ernaehrungskategorie: "omnivor",
    allergene: [],
    naehrwerte: { kcal: 480, eiweiss_g: 26, fett_g: 22, kohlenhydrate_g: 40 },
    zutaten: [
      { name: "Hackfleisch", gewicht: 4, essenziell: true },
      { name: "Kartoffel", gewicht: 4, essenziell: true },
      { name: "Karotte", gewicht: 1, essenziell: false },
      { name: "Zwiebel", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hackfleisch mit Zwiebel und Karotte anbraten.", "Kartoffeln kochen und zu Püree verarbeiten.", "Hackfleisch in eine Form geben, mit Kartoffelpüree bedecken und überbacken."],
  },
  {
    id: 62,
    name: "Paella",
    icon: "🥘",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 40,
    ernaehrungskategorie: "pescetarisch",
    allergene: ["Krebstiere"],
    naehrwerte: { kcal: 420, eiweiss_g: 24, fett_g: 12, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Reis", gewicht: 4, essenziell: true },
      { name: "Meeresfrüchte", gewicht: 4, essenziell: true },
      { name: "Paprika", gewicht: 1, essenziell: false },
      { name: "Erbsen", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reis in einer Pfanne andünsten.", "Mit Brühe aufgießen und köcheln lassen.", "Meeresfrüchte und Gemüse untermischen."],
  },
  {
    id: 63,
    name: "Veganer Burger",
    icon: "🍔",
    kategorie: "Mittag/Abend",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegan",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 460, eiweiss_g: 16, fett_g: 18, kohlenhydrate_g: 56 },
    zutaten: [
      { name: "Kichererbsen", gewicht: 4, essenziell: true },
      { name: "Burger-Brötchen", gewicht: 3, essenziell: true },
      { name: "Salat", gewicht: 1, essenziell: false },
      { name: "Avocado", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Kichererbsen pürieren und zu Laibchen formen.", "In der Pfanne braten.", "Im Brötchen mit Salat und Avocado servieren."],
  },

  // ---------- Süßspeise (neu) ----------
  {
    id: 64,
    name: "Tiramisu",
    icon: "🍰",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose", "Gluten", "Ei"],
    naehrwerte: { kcal: 420, eiweiss_g: 8, fett_g: 26, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Mascarpone", gewicht: 4, essenziell: true },
      { name: "Kaffee", gewicht: 2, essenziell: true },
      { name: "Löffelbiskuit", gewicht: 3, essenziell: true },
      { name: "Kakao", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Löffelbiskuit kurz in Kaffee tränken.", "Mit Mascarponecreme schichten.", "Mit Kakao bestäuben und kalt stellen."],
  },
  {
    id: 65,
    name: "Topfenknödel",
    icon: "🍡",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 40,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose", "Gluten"],
    naehrwerte: { kcal: 380, eiweiss_g: 14, fett_g: 14, kohlenhydrate_g: 48 },
    zutaten: [
      { name: "Topfen", gewicht: 4, essenziell: true },
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Butter", gewicht: 1, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Topfen und Mehl zu einem Teig verarbeiten.", "Knödel formen und in Salzwasser kochen.", "In Butterbröseln wälzen und mit Zucker bestreuen."],
  },
  {
    id: 66,
    name: "Panna Cotta",
    icon: "🍮",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 310, eiweiss_g: 5, fett_g: 22, kohlenhydrate_g: 22 },
    zutaten: [
      { name: "Milch", gewicht: 4, essenziell: true },
      { name: "Vanille", gewicht: 1, essenziell: true },
      { name: "Beeren", gewicht: 2, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Milch mit Vanille und Zucker erhitzen.", "In Förmchen füllen und kalt stellen, bis fest.", "Mit Beeren servieren."],
  },
  {
    id: 67,
    name: "Brownies",
    icon: "🍫",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 35,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Ei", "Nüsse"],
    naehrwerte: { kcal: 380, eiweiss_g: 6, fett_g: 20, kohlenhydrate_g: 44 },
    zutaten: [
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Kakao", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 2, essenziell: true },
      { name: "Nüsse", gewicht: 1, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Alle Zutaten zu einem Teig verrühren.", "In eine Form füllen.", "Bei 180°C ca. 25 Minuten backen."],
  },
  {
    id: 68,
    name: "Mohnnudeln",
    icon: "🍝",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten"],
    naehrwerte: { kcal: 420, eiweiss_g: 11, fett_g: 16, kohlenhydrate_g: 58 },
    zutaten: [
      { name: "Pasta", gewicht: 4, essenziell: true },
      { name: "Mohn", gewicht: 2, essenziell: true },
      { name: "Butter", gewicht: 1, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Nudeln in Salzwasser kochen.", "Mit zerlassener Butter vermengen.", "Mit Mohn und Zucker bestreuen."],
  },
  {
    id: 69,
    name: "Palatschinken mit Marillenmarmelade",
    icon: "🥞",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 20,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose", "Ei"],
    naehrwerte: { kcal: 340, eiweiss_g: 10, fett_g: 10, kohlenhydrate_g: 50 },
    zutaten: [
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Milch", gewicht: 3, essenziell: true },
      { name: "Ei", gewicht: 2, essenziell: true },
      { name: "Marmelade", gewicht: 2, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Mehl, Milch und Ei zu einem Teig verrühren.", "Dünne Palatschinken in der Pfanne backen.", "Mit Marmelade bestreichen und einrollen."],
  },
  {
    id: 70,
    name: "Vanillepudding",
    icon: "🍮",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 15,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 240, eiweiss_g: 6, fett_g: 7, kohlenhydrate_g: 38 },
    zutaten: [
      { name: "Milch", gewicht: 4, essenziell: true },
      { name: "Vanille", gewicht: 2, essenziell: true },
      { name: "Zucker", gewicht: 1, essenziell: false },
      { name: "Maisstärke", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Milch mit Vanille und Zucker erhitzen.", "Maisstärke einrühren, bis die Masse eindickt.", "In Gläser füllen und kalt stellen."],
  },
  {
    id: 71,
    name: "Zimtschnecken",
    icon: "🥐",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 60,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 380, eiweiss_g: 7, fett_g: 16, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Mehl", gewicht: 4, essenziell: true },
      { name: "Zimt", gewicht: 2, essenziell: true },
      { name: "Butter", gewicht: 2, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Hefeteig aus Mehl herstellen und gehen lassen.", "Mit Butter, Zimt und Zucker bestreichen und aufrollen.", "In Scheiben schneiden und backen."],
  },
  {
    id: 72,
    name: "Beeren-Crumble",
    icon: "🍓",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 35,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Gluten", "Laktose"],
    naehrwerte: { kcal: 320, eiweiss_g: 5, fett_g: 14, kohlenhydrate_g: 44 },
    zutaten: [
      { name: "Beeren", gewicht: 4, essenziell: true },
      { name: "Mehl", gewicht: 3, essenziell: true },
      { name: "Butter", gewicht: 2, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Beeren in eine Auflaufform geben.", "Mehl, Butter und Zucker zu Streuseln verarbeiten.", "Über die Beeren streuen und goldbraun backen."],
  },
  {
    id: 73,
    name: "Milchreis",
    icon: "🍚",
    kategorie: "Süßspeise",
    zubereitungszeit_min: 30,
    ernaehrungskategorie: "vegetarisch",
    allergene: ["Laktose"],
    naehrwerte: { kcal: 300, eiweiss_g: 8, fett_g: 7, kohlenhydrate_g: 52 },
    zutaten: [
      { name: "Reis", gewicht: 4, essenziell: true },
      { name: "Milch", gewicht: 4, essenziell: true },
      { name: "Zimt", gewicht: 1, essenziell: false },
      { name: "Zucker", gewicht: 1, essenziell: false },
    ],
    zubereitung: ["Reis mit Milch aufkochen.", "Bei kleiner Hitze 20 Minuten quellen lassen, gelegentlich rühren.", "Mit Zimt und Zucker servieren."],
  },
];

// Substitutionstabelle: welche Zutaten sich gegenseitig ersetzen können
const SUBSTITUTIONEN = {
  "Mehl": ["Maisstärke"],
  "Maisstärke": ["Mehl"],
  "Milch": ["Joghurtsauce", "Joghurt"],
  "Joghurtsauce": ["Milch"],
  "Joghurt": ["Milch"],
  "Ei": ["Apfelmus"],
  "Zucker": ["Honig"],
  "Honig": ["Zucker"],
  "Butter": ["Olivenöl"],
  "Olivenöl": ["Butter"],
};

// Zutaten gruppiert nach Kategorie, für eine übersichtliche Auswahl in der UI
const ZUTATEN_KATEGORIEN = {
  "Gemüse": ["Zwiebel", "Paprika", "Zucchini", "Karotte", "Sellerie", "Brokkoli", "Spinat", "Salat", "Mais", "Kartoffel", "Knoblauch", "Chili", "Avocado", "Petersilie", "Ingwer", "Erbsen", "Kürbis"],
  "Obst": ["Zitrone", "Äpfel", "Banane", "Orange", "Trauben", "Beeren", "Rosinen", "Trockenfrüchte", "Apfelmus"],
  "Fleisch & Fisch": ["Hühnerbrust", "Rindfleisch", "Speck", "Hackfleisch", "Lachs", "Thunfisch", "Schnitzel", "Meeresfrüchte"],
  "Pflanzliche Proteine": ["Tofu", "Kichererbsen", "Linsen", "Kidneybohnen"],
  "Milchprodukte & Eier": ["Milch", "Käse", "Butter", "Joghurtsauce", "Ei", "Parmesan", "Joghurt", "Frischkäse", "Topfen", "Mozzarella", "Feta", "Mascarpone"],
  "Getreide & Beilagen": ["Reis", "Pasta", "Spaghetti", "Spätzle", "Quinoa", "Mehl", "Haferflocken", "Tortilla", "Brot", "Blätterteig", "Bagel", "Pizzateig", "Burger-Brötchen", "Reisnudeln", "Lasagneplatten", "Couscous", "Gnocchi", "Löffelbiskuit"],
  "Gewürze & Sonstiges": ["Curry", "Kokosmilch", "Paprikapulver", "Kreuzkümmel", "Zimt", "Sojasauce", "Olivenöl", "Tahini", "Honig", "Zucker", "Puderzucker", "Maisstärke", "Kakao", "Nüsse", "Tomatensauce", "Kurkuma", "Basilikum", "Ketchup", "Misopaste", "Pesto", "Kaffee", "Vanille", "Mohn", "Marmelade"],
};

// Alle Zutaten, die in Rezepten vorkommen (abgeleitet, ohne Duplikate)
const ALLE_ZUTATEN = [...new Set(REZEPTE.flatMap((r) => r.zutaten.map((z) => z.name)))].sort();

// Alle Allergene, die in Rezepten vorkommen (für die Profil-Auswahl)
const ALLE_ALLERGENE = [...new Set(REZEPTE.flatMap((r) => r.allergene))].sort();

// Ernährungsoptionen für das Profil
const ERNAEHRUNGSOPTIONEN = ["", "vegan", "vegetarisch", "pescetarisch", "omnivor"];

// Mahlzeit-Kategorien zum Filtern
const KATEGORIEN = ["Alle", "Frühstück", "Mittag/Abend", "Süßspeise"];
